# Generated by Django 2.1.2 on 2018-10-31 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20181031_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='description',
        ),
    ]
