# Generated by Django 2.1.2 on 2018-11-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20181031_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='patient',
        ),
    ]
