# Generated by Django 2.1.2 on 2018-11-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20181109_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='desc',
            field=models.TextField(help_text='Enter the prescription : ', null=True, verbose_name='Prescription'),
        ),
    ]
