# Generated by Django 2.1.2 on 2018-11-10 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20181109_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.IntegerField(choices=[('1', 'Cardiology'), ('2', 'ENT'), ('3', 'Orthopaedics')], max_length=2, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='hosp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Hospital'),
        ),
    ]
