# Generated by Django 2.1.2 on 2018-11-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20181110_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.IntegerField(choices=[('1', 'Cardiology'), ('2', 'ENT'), ('3', 'Orthopaedics')], primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
