# Generated by Django 2.1.2 on 2018-11-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20181110_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ['id', 'depart']},
        ),
        migrations.AddField(
            model_name='hospital',
            name='depart',
            field=models.CharField(choices=[('1', 'Cardiology'), ('2', 'ENT'), ('3', 'Orthopaedics')], max_length=25, null=True, verbose_name='Hospital Dept'),
        ),
    ]
