# Generated by Django 2.1.2 on 2018-11-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20181110_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dop',
            field=models.DateField(null=True),
        ),
    ]
