# Generated by Django 2.1.2 on 2018-11-10 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20181110_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='drugid',
            field=models.IntegerField(null=True, verbose_name='DrugID'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='drug',
            field=models.ForeignKey(help_text='Enter the drug id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Pharmacy'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
